### ISSUE TITLE
[Batch] parallelization for batched registers

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/Yao.jl#13]
Batched registers can be parallelized on the last dimension (batch dimension).

For CPU arrays, there is two options: 
- use `SharedArray` to parallel it among process, which will allow us to process between nodes on a Julia sever
- use `thread` in stdlib, this may have less overhead, but it won't run on multiple CPU nodes

**Comment by GiggleLiu** [comment]
There are too many parallism schemes, a better question would be "what kind of problem do we expect to solve using parallism?".

To me, MPI support to parallelize the functions to get gradient (i.e. `opdiff`, `opdiff` and `statdiff`) is important to our goal "Quantum Software 2.0". This is also an achievable simple goal in Yao.jl 0.3.0.

By this consideration, I suggest to put the parallism on Blocks rather than Registers.

**Comment by Roger-luo** [comment]
in dup with https://github.com/QuantumBFS/YaoArrayRegister.jl/pull/19

It is implemented, but we need to wait for that bug fix...
