### ISSUE TITLE
CZ gate should be added to Yao.ConstGate

### ISSUE THREAD

**Issue by yihong-zhang** [QuantumBFS/Yao.jl#197]
FYI.

**Comment by Roger-luo** [comment]
This should be straight forward, try your first PR? @yihong-zhang

**Comment by Roger-luo** [comment]
In case you didn't find it: https://github.com/QuantumBFS/YaoBlocks.jl/blob/master/src/primitive/const_gate_gen.jl

BTW, I'm still wondering what is the use case for a constant gate `CZ`? it is just `control(a, b=>Z)` right?

**Comment by yihong-zhang** [comment]
> In case you didn't find it: https://github.com/QuantumBFS/YaoBlocks.jl/blob/master/src/primitive/const_gate_gen.jl
> 
> BTW, I'm still wondering what is the use case for a constant gate `CZ`? it is just `control(a, b=>Z)` right?

Yes. CZ is an symmetric entangled gate and quite different from CNOT (asymmetric). CZ is very important in quantum information, for example, it is frequently used in cluster states generations, which are key sources in measurement-based quantum computing.

**Comment by GiggleLiu** [comment]
Just like `cnot(nbit, i, j)`, besides `CZ`, we should probably also have `cz(nbit, i, j)`. @yihong-zhang 

@Roger-luo Constant CZ gates can be used in `rot` blocks, this is the using case of Yi-Hong, otherwise, we can just use `cz(nbit, i, j)` interface. BTW: Do you think it is good to  to have `put(nbit, (i,j)=>CNOT)` and `put(nbit, (i,j)=>CZ)` being dispatched to faster control blocks?

**Comment by Roger-luo** [comment]
The whole reason we hide those constant gates is because they are confusing with existing composite blocks (#163), I think the point of avoiding such thing is because:

a) we don't want to have many alternative to implement the same task which can be confusing and hard to maintain and test
b) they are slower than those composite blocks since it is not specialized to low level instruct (due to more complicated maintenance, we can't guarantee each possible implementation is always dispatched to correct place)

Regarding to the constant CZ, I think the problem is because you don't want to re-allocate the matrix during calculation? or why you can't use `control(a, b=>Z)` in rot? e.g

```jl
rot(control(2, 1, 2=>Z), 1.0)
``` 

It seems to just work for me. And yes, if it is just for convenience we should add `cz` instead of `CZ` as constant gate.

**Comment by Roger-luo** [comment]
> Do you think it is good to to have put(nbit, (i,j)=>CNOT) and put(nbit, (i,j)=>CZ) being dispatched to faster control blocks?

I'd prefer to encourage to use `control` as much as possible, it seems the only difference of using a constant gate `CZ` instead of `control(a, b=>Z)` is a 96 byte extra allocation each time you call `mat`. The rest can be the same (we can dispatch `apply!` of `CZ` to specific `instruct`)

Regarding to the original proposal, I think we can specialize high level interface as much as possible, this won't make any difference on the interface at this level, the code is completely equivalent (using `control Z` instruct or `control U` instruct).

**Comment by GiggleLiu** [comment]
so the final decision is
1. define CZ without export to Yao, one has to import `Yao.ConstGate` as before, someone complaint that the interface for `swap` is too ambiguous.
2. define a function `cz(nbit, i, j)` to be used as a gate, `CZ` should be regarded as a generator/matrix rather than a unitary gate.

Do you agree? @yihong-zhang

**Comment by Roger-luo** [comment]
I think her issue is about printing instead of constant gate. We should overload the show function for control block as well. I think a one line compat printing mode is necessary now, (like the Array printing in Base) I thought about it before, but I didn't have any use case so I didn't implement it.

**Comment by yihong-zhang** [comment]
> 2\. define a function `cz(nbit, i, j)`

**Comment by yihong-zhang** [comment]
> so the final decision is
> 
> 1. define CZ without export to Yao, one has to import `Yao.ConstGate` as before, someone complaint that the interface for `swap` is too ambiguous.
> 2. define a function `cz(nbit, i, j)` to be used as a gate, `CZ` should be regarded as a generator/matrix rather than a unitary gate.
> 
> Do you agree? @yihong-zhang

I will define a function cz(nbit, i, j) later.

**Comment by Roger-luo** [comment]
solved by https://github.com/QuantumBFS/YaoBlocks.jl/pull/82
