### ISSUE TITLE
Add a coverage badge

### ISSUE THREAD

**Issue by kshyatt** [QuantumBFS/Yao.jl#230]
It's nice to have in the README, and your coverage is so good it would be nice to show it off.

**Comment by GiggleLiu** [comment]
Yao.jl is a meta package,  code coverage is shown in 

https://github.com/QuantumBFS/YaoBlocks.jl
https://github.com/QuantumBFS/YaoArrayRegister.jl

Maybe showing the test coverage of YaBlocks in README?

@Roger-luo

**Comment by Roger-luo** [comment]
If we are gonna show the test coverage, we should list all the components test coverage. Not just YaoBlocks. I could add a table of this.

**Comment by Roger-luo** [comment]
@kshyatt so I just added badges, the coverage of [YaoBase](https://github.com/QuantumBFS/YaoBase.jl) is pretty low, but since it's just abstract interfaces, we didn't push this coverage up very high. The rest component packages are just OK actually. 

I'll close this issue since it's done now. thanks for the suggestion.
