### ISSUE TITLE
SymEngine dependence 

### ISSUE THREAD

**Issue by lucasvreis** [QuantumBFS/Yao.jl#240]
Hi, I'm taking a quantum theory course and learning Yao so I can experiment with the theory a bit.

The Yao docs say:
> `@ket_str`
> Create a ket register. See also `@bra_str`.
> 
> Example
> 
> a symbolic quantum state can be created simply by:
> 
> `julia> ket"110" + 2ket"111"`
> `|110⟩ + 2|111⟩`

But it took me a while before I found this macro only works after I do `import SymEngine`.
I am not sure if this is intended, in which case my suggestion is to have it explained in the documentation, or if Yao should be importing SymEngine behind-the-scenes and something went wrong.

Nevertheless, thank you for this very cool package.

**Comment by Roger-luo** [comment]
Hi @lucasvreis thanks for your issue,

indeed, now you need to `using SymEngine` explicitly, and Yao will not depends on SymEngine anymore, since we keep receiving reports from users that SymEngine is causing installation failure of Yao due to its binary dependencies.

But this is not an intuitive error, and we need to polish this error msg indeed.

**Comment by Roger-luo** [comment]
should be fixed by https://github.com/QuantumBFS/YaoSym.jl/commit/8575718c1fed76ca99907cd2f51c7331a021577d
