### ISSUE TITLE
NoParams and non-inplace dispatch

### ISSUE THREAD

**Issue by vincentelfving** [QuantumBFS/Yao.jl#327]
I'm trying to `dispatch` (not `dispatch!`) on a set of blocks where one or more blocks has been tagged as NoParams.
```
using YaoBlocks
u = chain(1, YaoBlocks.AD.NoParams(Yao.Ry(1.0)), Yao.Rx(1.0))
dispatch!(u, [2.0]) # works as expected, modifying the Rx gate's parameter to 2.0 and keeping Ry fixed to original 1.0
dispatch(u, [2.0]) # returns the following error 
ERROR: NotImplementedError: chsubblocks is not implemented for (::YaoBlocks.AD.NoParams{1, RotationGate{1, Float64, YGate}}, ::RotationGate{1, Float64, YGate}), please implement this method for your custom type
```
Then I tried implementing `chsubblocks` for the NoParams case as 
```
YaoBlocks.chsubblocks(x::YaoBlocks.AD.NoParams, y::AbstractBlock)=YaoBlocks.AD.NoParams(y)
```
but then I get a different error
```
dispatch(u, [2.0])
ERROR: BoundsError: attempt to access 1-element Vector{Float64} at index [2:2]
```
and now I'm not sure what to do next. It seems like somehow it still expects 2 parameters and the NoParams tag was ignored, because the above error is identical to the one I see when trying `dispatch(chain(1, Yao.Ry(1.0), Yao.Rx(1.0)), [2.0])`

It's probably trivial, but could you help me out? Thanks!

**Comment by GiggleLiu** [comment]
Oops, I was trying to checkout a new branch and create a PR to resolve this issue, but turns out the branch name is not specified correctly. I pushed to the master directly by mistake. @Roger-luo 
This is the relevant commit:
https://github.com/QuantumBFS/Yao.jl/commit/dcc66a1a93b1929927add25de745b880c35c2aaf

@vincentelfving it should be fixed in the master.

**Comment by vincentelfving** [comment]
@GiggleLiu thanks a lot! this is indeed fixed now
